import MaleyLean.AmetricPaperStatements

namespace MaleyLean

#print axioms PaperAmetricCollapseStatement
#print axioms PaperStandingContentStatement
#print axioms PaperFailureRegionContentStatement
#print axioms PaperIrrecoverabilityMetricInvarianceStatement
#print axioms PaperStandingPreservationCompositionStatement
#print axioms PaperClosurePropagationStatement
#print axioms PaperIntermediateContainmentExclusionStatement
#print axioms PaperCompositeUnusabilityDecompositionStatement
#print axioms PaperNoDeferredRepairTwoStepStatement
#print axioms PaperNoDeferredRepairTwoStepBlocksLegalityStatement
#print axioms PaperNoDeferredRepairTwoStepUnusabilityStatement
#print axioms PaperNoStagedRepairThreeStepStatement
#print axioms PaperNoStagedRepairThreeStepBlocksLegalityStatement
#print axioms PaperNoStagedRepairThreeStepUnusabilityStatement
#print axioms PaperNoFiniteRepairFourStepStatement
#print axioms PaperNoFiniteRepairFourStepBlocksLegalityStatement
#print axioms PaperNoFiniteRepairFourStepUnusabilityStatement
#print axioms PaperChainThreeCompositionStandingPreservationStatement
#print axioms PaperChainFourCompositionStandingPreservationStatement
#print axioms PaperChainThreeIrrecoverabilityStatement
#print axioms PaperChainThreeBlocksLegalityStatement
#print axioms PaperChainThreeYieldsUnusabilityStatement
#print axioms PaperChainFourIrrecoverabilityStatement
#print axioms PaperChainFourBlocksLegalityStatement
#print axioms PaperChainFourYieldsUnusabilityStatement
#print axioms PaperStandingBivalenceStatement
#print axioms PaperBivalenceUniquenessStatement

end MaleyLean
