import MaleyLean.BivalentTrajectoryPaperStatements

namespace MaleyLean

#print axioms PaperTrajectoryStandingBivalenceStatement
#print axioms PaperTrajectoryStandingPreservationCompositionStatement
#print axioms PaperTrajectoryClosurePropagationStatement
#print axioms PaperTrajectoryCompositeUnusabilityDecompositionStatement
#print axioms PaperTrajectoryNoDeferredRepairTwoStepStatement
#print axioms PaperTrajectoryNoDeferredRepairTwoStepBlocksLegalityStatement
#print axioms PaperTrajectoryNoDeferredRepairTwoStepUnusabilityStatement
#print axioms PaperTrajectoryNoStagedRepairThreeStepStatement
#print axioms PaperTrajectoryNoStagedRepairThreeStepBlocksLegalityStatement
#print axioms PaperTrajectoryNoStagedRepairThreeStepUnusabilityStatement
#print axioms PaperTrajectoryNoFiniteRepairFourStepStatement
#print axioms PaperTrajectoryNoFiniteRepairFourStepBlocksLegalityStatement
#print axioms PaperTrajectoryNoFiniteRepairFourStepUnusabilityStatement
#print axioms PaperTrajectoryChainThreeCompositionStatement
#print axioms PaperTrajectoryChainFourCompositionStatement
#print axioms PaperTrajectoryChainThreeIrrecoverabilityStatement
#print axioms PaperTrajectoryChainThreeBlocksLegalityStatement
#print axioms PaperTrajectoryChainThreeUnusabilityStatement
#print axioms PaperTrajectoryChainFourIrrecoverabilityStatement
#print axioms PaperTrajectoryChainFourBlocksLegalityStatement
#print axioms PaperTrajectoryChainFourUnusabilityStatement

end MaleyLean
