import MaleyLean.EmpiricalCompletenessPaperStatements

namespace MaleyLean

#print axioms PaperTargetIdentityFromStabilityStatement
#print axioms PaperOrbitFixationFromConfirmationStatement
#print axioms PaperNonFixedReferenceBlocksTheoryLevelConfirmationStatement
#print axioms PaperCompletenessDoesNotSubstituteForFixationStatement
#print axioms PaperAdmissibleFixationEnablesTheoryLevelConfirmationStatement
#print axioms PaperTheoryLevelConfirmationPossibleFromFixationStatement
#print axioms PaperAssignmentRelativityFromMultipleAdmissibleAssignmentsStatement
#print axioms PaperConfirmationCollapseAssignmentStatement
#print axioms PaperAssignmentRelativityOfConfirmationJudgmentsStatement
#print axioms PaperConfirmationCollapseDiscriminatorFailureStatement
#print axioms PaperGaugeRedundancyIsNotReferenceUnderdeterminationStatement

end MaleyLean
