import MaleyLean.Papers.NavierStokes.Continuation.Boundary

namespace MaleyLean

#print axioms PaperContinuationRelevanceFactorsThroughQuotientStatement
#print axioms PaperSingularExtractorFactorsThroughQuotientStatement
#print axioms PaperExtractorOutputsSameScopeStatement
#print axioms PaperSingularExtractorNoSecondGateStatement
#print axioms PaperContinuationBoundaryClosedStatement

end MaleyLean
