import MaleyLean.Papers.NavierStokes.Primitive.Bridge

namespace MaleyLean

#print axioms PaperCarrierToLineageBindingStatement
#print axioms PaperStandingPositiveLineageStatement
#print axioms PaperNoAdmissibilityDynamicsStatement
#print axioms PaperPreHorizonWitnessStatement
#print axioms PaperSingularCandidateTypingStatement
#print axioms PaperMetricDivergenceSkinNonAuthorityStatement
#print axioms PaperQuotientVisibleWitnessVsIllicitMetricGateStatement
#print axioms PaperVortexStretchingAnomalyBoundaryStatement
#print axioms PaperPrimitiveToPDEBridgeBoundaryStatement

end MaleyLean
