import MaleyLean.Papers.StandardModel.Support.NeutrinoMixing.DerivedPaperStatements

namespace MaleyLean

#print axioms PaperNeutrinoMixingInvariantSurfaceStatement
#print axioms PaperNoIndependentOscillationDegreeStatement
#print axioms PaperNeutrinoSharedWitnessPairStatement
#print axioms PaperNoNeutrinoWitnessPairSplitStatement

end MaleyLean
