import MaleyLean.Papers.StandardModel.Support.Rephasing.DerivedPaperStatements

namespace MaleyLean

#print axioms PaperRephasingRedundancyStatement
#print axioms PaperNoResidualRephasingStatement
#print axioms PaperRephasingSharedWitnessStatement
#print axioms PaperNoRephasingWitnessSplitStatement

end MaleyLean
