import MaleyLean.Papers.StandardModel.Structural.MetaClosureStatements

namespace MaleyLean

#print axioms PaperStandardModelStandingQuotientUniquenessStatement
#print axioms PaperStandardModelNoStandingRepairStatement
#print axioms PaperStandardModelNoCanonicalRepresentativeStatement
#print axioms PaperStandardModelStructuralVerifiedCoreStatement
#print axioms PaperStandardModelStructuralMetaClosureStatement

end MaleyLean
