import MaleyLean.YangMillsTheoremAssemblyNativeInterHeartAlignmentSummary

namespace MaleyLean

#print axioms YangMillsTheoremAssemblyNativeInterHeartAlignmentSummaryTopExportStatement

end MaleyLean
