import MaleyLean.YangMillsAssemblyTopNativeCrossHeartFactorizationLawTrianglePackageSummary

open MaleyLean

#print axioms YangMillsAssemblyTopNativeCrossHeartFactorizationLawTrianglePackageSummaryExportStatement
