import MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationTriangleAlignment

#print axioms MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationTriangleAlignmentExportWrapperStatement
