import MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawAlignment

open MaleyLean

#print axioms YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawAlignmentExportStatementWrapper
