import MaleyLean.YangMillsConstructiveManuscriptWitnessDeclarationsSummary

namespace MaleyLean

#print axioms YangMillsConstructiveManuscriptWitnessDeclarationsSummaryTopExportStatement

end MaleyLean
