import MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTrianglePackageAlignment

open MaleyLean

#print axioms YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTrianglePackageAlignmentExportStatementWrapper
