import MaleyLean.YangMillsAssemblyTopNativeCrossHeartFactorizationLawTriangleNamedLawsSummary

open MaleyLean

#print axioms YangMillsAssemblyTopNativeCrossHeartFactorizationLawTriangleNamedLawsSummaryExportStatement
