import MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTriangleAlignment

open MaleyLean

#print axioms YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTriangleAlignmentExportStatementWrapper
