import MaleyLean.YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTriangleNamedLawsAlignment

open MaleyLean

#print axioms YangMillsTheoremAssemblyNativeCrossHeartFactorizationLawTriangleNamedLawsAlignmentExportStatementWrapper
