import MaleyLean.NavierStokesPDEObligationInventory

namespace MaleyLean

#print axioms PaperObligationInventoryCompleteStatement
#print axioms PaperAnalyticInventoryReducesToNamedFailureStatement
#print axioms PaperConcreteRegisterMatchesInventoryStatement
#print axioms PaperConcreteRegisterHasNamedFailureStatement
#print axioms PaperConcreteRegisterReducesAnalyticBurdenStatement

end MaleyLean
