import MaleyLean.PrimitiveToPeriodicLocalTheory
import MaleyLean.NavierStokesQuotientFactorization

namespace MaleyLean

#print axioms PaperFutureBehaviorQuotientStatement
#print axioms PaperHistoryFactorizationNoPathDependentAdmissibilityStatement
#print axioms PaperSameScopeDiscriminatorFactorizationStatement
#print axioms PaperNoSecondGateSameScopeStatement
#print axioms PaperPrimitivePeriodicPacketWithQuotientStatement

end MaleyLean
