import MaleyLean.NavierStokesVerbatimDependencySpineSimple

namespace MaleyLean

#print axioms PaperVerbatimStructuralTitlesClosedSimpleStatement
#print axioms PaperVerbatimNamedFailureTitleSimpleStatement
#print axioms PaperVerbatimEndpointTitlesSimpleStatement
#print axioms PaperVerbatimSupportDependencyAlignmentSimpleStatement

end MaleyLean
