import MaleyLean.NavierStokesDraftClaimRegister

namespace MaleyLean

#print axioms PaperDraftRegisterClassificationStatement
#print axioms PaperDraftRegisterAgreesWithPaperClaimLedgerStatement
#print axioms PaperDraftStructuralClaimsCertifiedStatement
#print axioms PaperDraftNamedFailureBoundaryStatement
#print axioms PaperDraftEndpointGapStatement
#print axioms PaperDraftRegisterInheritsStructuralAlignmentStatement

end MaleyLean
