import MaleyLean.PrimitiveToPeriodicLocalTheory

namespace MaleyLean

#print axioms PaperDatumEntryToAdmittedCarrierStatement
#print axioms PaperLocalRealizationOnCarrierStatement
#print axioms PaperRestartConsistencySameObjectPersistenceStatement
#print axioms PaperPreHorizonSliceReentryStatement
#print axioms PaperFiniteHorizonWitnessVisibilityStatement
#print axioms PaperPrimitivePeriodicLocalTheoryPacketStatement
#print axioms PaperPrimitiveBridgeCompatibleWithAnomalyBoundaryStatement

end MaleyLean
