import MaleyLean.NavierStokesPaperObligationLedger
namespace MaleyLean
#print axioms NSPaperSection.casesOn
#print axioms section_obligation
#print axioms section_is_named_failure_boundary
#print axioms section_depends_on_named_failure
end MaleyLean
