import MaleyLean.Papers.YangMills.Surface.CanonicalVerifiedPayloadSummary

namespace MaleyLean

abbrev YangMillsCanonicalVerifiedPayloadSummaryTopExportStatement :=
  YangMillsCanonicalVerifiedPayloadSummaryStatement

end MaleyLean
