import MaleyLean.Papers.YangMills.Surface.DependencySkeleton
import MaleyLean.Papers.YangMills.Obligations.Inventory
import MaleyLean.Papers.YangMills.Obligations.PaperLedger
import MaleyLean.Papers.YangMills.Obligations.ClaimLedger
import MaleyLean.Papers.YangMills.Kernel.Register
import MaleyLean.Papers.YangMills.Kernel.PacketRegister
import MaleyLean.Papers.YangMills.Kernel.CoreAssembly
import MaleyLean.Papers.YangMills.Kernel.ConstructiveCore
import MaleyLean.Papers.YangMills.Kernel.EndpointAlignment
import MaleyLean.Papers.YangMills.Kernel.EndpointCore
import MaleyLean.Papers.YangMills.Kernel.LoadBearingSpine
import MaleyLean.Papers.YangMills.Kernel.NamedOutputsAssembly
import MaleyLean.Papers.YangMills.Kernel.ReadingOrder
import MaleyLean.Papers.YangMills.Kernel.SeamRegister
import MaleyLean.Papers.YangMills.Kernel.TheoremPartAlignment
import MaleyLean.Papers.YangMills.Kernel.VacuumGapCore
import MaleyLean.Papers.YangMills.SourceCrosswalk.Register
import MaleyLean.Papers.YangMills.SourceCrosswalk.CompanionTables
import MaleyLean.Papers.YangMills.SourceCrosswalk.ConstructiveWitnessRegister
import MaleyLean.Papers.YangMills.SourceCrosswalk.WitnessRegister
import MaleyLean.Papers.YangMills.SourceCrosswalk.VacuumGapWitnessRegister
import MaleyLean.Papers.YangMills.Verbatim.TheoremRegister
import MaleyLean.Papers.YangMills.Verbatim.DependencySpineSimple
import MaleyLean.Papers.YangMills.Surface.Summary
import MaleyLean.Papers.YangMills.Surface.SummaryWitnessed
